/**
 * Central endpoint catalogue.
 *
 * One place that knows the REST surface, so slices, hooks and pages never
 * hand-assemble URL strings (which is where 404s and typos hide). Paths are
 * relative to the axios `baseURL` (`/api`). Query params are appended by
 * callers via `request.get(url, { params })`, so these builders stay pure.
 */

export const endpoints = {
  // ---- auth / identity ----
  auth: {
    me: '/auth/me',
    flags: '/auth/flags',
    profile: '/auth/profile',
    candidateProfile: '/auth/profile/candidate',
    instructorProfile: '/auth/profile/instructor',
    acceptInvite: '/auth/invites/accept',
    deactivate: '/auth/account/deactivate',
    reactivate: '/auth/account/reactivate',
  },

  // ---- organizations ----
  organizations: {
    mine: '/organizations/mine',
    list: '/organizations',
    root: '/organizations',
    byId: (id) => `/organizations/${id}`,
    members: (id) => `/organizations/${id}/members`,
    member: (id, userId) => `/organizations/${id}/members/${userId}`,
    // NOTE: the create-invite write is `POST /:id/members/invite` on the server,
    // while listing/resending/revoking live under `/invites`. Keep both.
    invite: (id) => `/organizations/${id}/members/invite`,
    invites: (id) => `/organizations/${id}/invites`,
    resendInvite: (id, inviteId) => `/organizations/${id}/invites/${inviteId}/resend`,
    revokeInvite: (id, inviteId) => `/organizations/${id}/invites/${inviteId}`,
    departments: (id) => `/organizations/${id}/departments`,
    settings: (id) => `/organizations/${id}/settings`,
    subscription: (id) => `/organizations/${id}/subscription`,
  },

  // ---- exams ----
  exams: {
    mine: '/exams/mine',
    catalog: '/exams/catalog',
    list: '/exams',
    root: '/exams',
    byId: (id) => `/exams/${id}`,
    byToken: (token) => `/exams/invite/${token}`,
    publish: (id) => `/exams/${id}/publish`,
    clone: (id) => `/exams/${id}/clone`,
    archive: (id) => `/exams/${id}/archive`,
    versions: (id) => `/exams/${id}/versions`,
    restoreVersion: (id, versionId) => `/exams/${id}/versions/${versionId}/restore`,
    dashboard: (id) => `/exams/${id}/dashboard`,
    authorOverview: (id) => `/exams/${id}/author-overview`,
    sections: (id) => `/exams/${id}/sections`,
    section: (id, sectionId) => `/exams/${id}/sections/${sectionId}`,
    sectionPool: (id, sectionId) => `/exams/${id}/sections/${sectionId}/pool`,
    questions: (id) => `/exams/${id}/questions`,
    reorderQuestions: (id) => `/exams/${id}/questions/reorder`,
    removeQuestion: (id, questionId) => `/exams/${id}/questions/${questionId}`,
    candidates: (id) => `/exams/${id}/candidates`,
    assignCandidates: (id) => `/exams/${id}/candidates/assign`,
    removeCandidate: (id, userId) => `/exams/${id}/candidates/${userId}`,
    regenerateTokens: (id) => `/exams/${id}/tokens/regenerate`,
    recompute: (id) => `/exams/${id}/recompute`,
    preview: (id) => `/exams/${id}/preview`,
  },

  // ---- questions ----
  questions: {
    list: '/questions',
    root: '/questions',
    byId: (id) => `/questions/${id}`,
    search: '/questions/search',
    facets: '/questions/facets',
    reviewQueue: '/questions/review-queue',
    review: (id) => `/questions/${id}/review`,
    versions: (id) => `/questions/${id}/versions`,
    restoreVersion: (id, versionId) => `/questions/${id}/versions/${versionId}/restore`,
    duplicate: (id) => `/questions/${id}/duplicate`,
    archive: (id) => `/questions/${id}/archive`,
    moveToBank: (id) => `/questions/${id}/move-to-bank`,
    related: (id) => `/questions/${id}/related`,
    nlSearch: '/questions/nl-search',
  },

  // ---- question banks ----
  questionBanks: {
    list: '/question-banks',
    accessible: '/question-banks/accessible',
    root: '/question-banks',
    byId: (id) => `/question-banks/${id}`,
    categories: (id) => `/question-banks/${id}/categories`,
    category: (id, categoryId) => `/question-banks/${id}/categories/${categoryId}`,
    insights: (id) => `/question-banks/${id}/insights`,
    duplicates: (id) => `/question-banks/${id}/duplicates`,
    share: (id) => `/question-banks/${id}/share`,
    revokeShare: (id, shareId) => `/question-banks/${id}/share/${shareId}`,
    recount: (id) => `/question-banks/${id}/recount`,
    import: (id) => `/question-banks/${id}/import`,
    export: '/question-banks/export',
    template: '/question-banks/import-template',
  },

  // ---- attempts / taking exams ----
  attempts: {
    mine: '/attempts/mine',
    register: (examId) => `/attempts/exams/${examId}/register`,
    start: (examId) => `/attempts/exams/${examId}/start`,
    byId: (id) => `/attempts/${id}`,
    beginClock: (id) => `/attempts/${id}/begin-clock`,
    runtime: (id) => `/attempts/${id}/runtime`,
    answer: (id) => `/attempts/${id}/answers`,
    autosave: (id) => `/attempts/${id}/autosave`,
    sync: (id) => `/attempts/${id}/sync`,
    navigate: (id) => `/attempts/${id}/navigate`,
    markForReview: (id) => `/attempts/${id}/mark-for-review`,
    revealHint: (id) => `/attempts/${id}/hint`,
    runTests: (id) => `/attempts/${id}/run-tests`,
    pause: (id) => `/attempts/${id}/pause`,
    resume: (id) => `/attempts/${id}/resume`,
    submit: (id) => `/attempts/${id}/submit`,
    results: (id) => `/attempts/${id}/results`,
    review: (id) => `/attempts/${id}/review`,
    share: (id) => `/attempts/${id}/share`,
    shared: (token) => `/attempts/shared/${token}`,
    terminate: (id) => `/attempts/${id}/terminate`,
    list: '/attempts',
    // live quiz — routes mirror server attempt.routes.js: `join/leave` are keyed
    // by the human-readable join `code`; host actions are keyed by `sessionId`.
    createLiveQuiz: (examId) => `/attempts/live/exams/${examId}/sessions`,
    liveSession: (code) => `/attempts/live/join/${code}`,
    liveJoin: (code) => `/attempts/live/join/${code}`,
    liveLeave: (code) => `/attempts/live/leave/${code}`,
    liveAdvance: (sessionId) => `/attempts/live/sessions/${sessionId}/advance`,
    liveCloseQuestion: (sessionId) => `/attempts/live/sessions/${sessionId}/close-question`,
    liveEnd: (sessionId) => `/attempts/live/sessions/${sessionId}/end`,
    liveAnswer: (sessionId) => `/attempts/live/sessions/${sessionId}/answer`,
    liveLeaderboard: (sessionId) => `/attempts/live/sessions/${sessionId}/leaderboard`,
  },

  // ---- proctoring ----
  proctoring: {
    setup: (attemptId) => `/proctoring/${attemptId}/setup`,
    setupComplete: (attemptId) => `/proctoring/${attemptId}/setup/complete`,
    retrySetup: (attemptId) => `/proctoring/${attemptId}/setup/retry`,
    presence: (attemptId) => `/proctoring/${attemptId}/presence`,
    requirements: (examId) => `/proctoring/exams/${examId}/requirements`,
    dashboard: (examId) => `/proctoring/exams/${examId}/dashboard`,
    live: '/proctoring/live',
    snapshot: (attemptId) => `/proctoring/${attemptId}/snapshot`,
    stats: (examId) => `/proctoring/exams/${examId}/stats`,
    violations: (attemptId) => `/proctoring/${attemptId}/violations`,
    timeline: (attemptId) => `/proctoring/${attemptId}/violations/timeline`,
    recordings: (attemptId) => `/proctoring/${attemptId}/recordings`,
    finaliseRecording: (recordingId) => `/proctoring/recordings/${recordingId}/finalise`,
    gallery: (examId) => `/proctoring/exams/${examId}/recordings`,
    messages: (attemptId) => `/proctoring/${attemptId}/messages`,
    reply: (attemptId) => `/proctoring/${attemptId}/messages/reply`,
    unread: '/proctoring/messages/unread',
    pause: (attemptId) => `/proctoring/${attemptId}/pause`,
    resume: (attemptId) => `/proctoring/${attemptId}/resume`,
    terminate: (attemptId) => `/proctoring/${attemptId}/terminate`,
    extraTime: (attemptId) => `/proctoring/${attemptId}/extra-time`,
    flag: (attemptId) => `/proctoring/${attemptId}/flag`,
    reviewQueue: '/proctoring/review-queue',
    reviewSummary: (examId) => `/proctoring/exams/${examId}/review-summary`,
    aiRisk: (attemptId) => `/proctoring/${attemptId}/risk`,
    approveSetup: (sessionId) => `/proctoring/sessions/${sessionId}/approve`,
    rejectSetup: (sessionId) => `/proctoring/sessions/${sessionId}/reject`,
  },

  // ---- grading ----
  // Mirrors server grading.routes.js exactly: the grading write is `POST
  // /grading/grade` with the answerId in the body, not an answer-scoped URL.
  grading: {
    queue: '/grading/queue',
    myQueue: '/grading/my-queue',
    submission: (answerId) => `/grading/answers/${answerId}/submission`,
    grade: '/grading/grade',
    gradeMany: '/grading/grade-many',
    rubricScores: (answerId) => `/grading/answers/${answerId}/rubric-scores`,
    attemptSubmissions: (attemptId) => `/grading/attempts/${attemptId}/submissions`,
    // convenience alias — same endpoint, reads better from a queue page
    // that only has attempt ids and needs the first pending answer to link to.
    attemptAnswers: (attemptId) => `/grading/attempts/${attemptId}/submissions`,
    finalise: (attemptId) => `/grading/attempts/${attemptId}/finalise`,
    feedback: (attemptId) => `/grading/attempts/${attemptId}/feedback`,
    assign: '/grading/assignments',
    release: (examId) => `/grading/exams/${examId}/release`,
    stats: (examId) => `/grading/exams/${examId}/stats`,
    forecast: (examId) => `/grading/exams/${examId}/forecast`,
    aiEssay: (answerId) => `/grading/answers/${answerId}/ai-essay`,
    aiCode: (answerId) => `/grading/answers/${answerId}/ai-code`,
    aiFeedback: (attemptId) => `/grading/attempts/${attemptId}/personalised-feedback`,
  },

  // ---- certificates ----
  certificates: {
    mine: '/certificates/mine',
    list: '/certificates',
    root: '/certificates',
    byId: (id) => `/certificates/${id}`,
    download: (id) => `/certificates/${id}/download`,
    linkedin: (id) => `/certificates/${id}/linkedin`,
    verifyByToken: (token) => `/certificates/verify/${token}`,
    verify: '/certificates/verify',
    verifySignature: '/certificates/verify-signature',
    badge: (certificateNo) => `/certificates/badge/${certificateNo}`,
    templates: '/certificates/templates',
    template: (id) => `/certificates/templates/${id}`,
    templatePreview: (id) => `/certificates/templates/${id}/preview`,
    defaultTemplate: (id) => `/certificates/templates/${id}/default`,
    issue: '/certificates/issue',
    issueBulk: (examId) => `/certificates/exams/${examId}/issue-bulk`,
    revoke: (id) => `/certificates/${id}/revoke`,
    restore: (id) => `/certificates/${id}/restore`,
    reissue: (id) => `/certificates/${id}/reissue`,
    email: (id) => `/certificates/${id}/email`,
    emailExam: (examId) => `/certificates/exams/${examId}/email-all`,
    eligibility: (attemptId) => `/certificates/attempts/${attemptId}/eligibility`,
    stats: '/certificates/stats',
  },

  // ---- analytics ----
  analytics: {
    organization: '/analytics/organization',
    examOverview: (examId) => `/analytics/exams/${examId}/overview`,
    scoreDistribution: (examId) => `/analytics/exams/${examId}/score-distribution`,
    time: (examId) => `/analytics/exams/${examId}/time`,
    questions: (examId) => `/analytics/exams/${examId}/questions`,
    topics: (examId) => `/analytics/exams/${examId}/topics`,
    candidates: (examId) => `/analytics/exams/${examId}/candidates`,
    violations: (examId) => `/analytics/exams/${examId}/violations`,
    trend: (examId) => `/analytics/exams/${examId}/trend`,
    survey: (examId) => `/analytics/exams/${examId}/survey`,
    exportAnalytics: (examId) => `/analytics/exams/${examId}/export/analytics`,
    exportResults: (examId) => `/analytics/exams/${examId}/export/results`,
    aiQuality: (examId) => `/analytics/exams/${examId}/ai/quality`,
    aiPassRate: (examId) => `/analytics/exams/${examId}/ai/pass-rate`,
    aiSummary: (examId) => `/analytics/exams/${examId}/ai/summary`,
    myHistory: '/analytics/me/history',
    candidateHistory: (userId) => `/analytics/candidates/${userId}/history`,
  },

  // ---- notifications ----
  notifications: {
    list: '/notifications',
    root: '/notifications',
    byId: (id) => `/notifications/${id}`,
    stats: '/notifications/stats',
    readAll: '/notifications/read-all',
    clearRead: '/notifications/clear-read',
    preferences: '/notifications/preferences',
    announcements: '/notifications/announcements',
    dismissAnnouncement: (id) => `/notifications/announcements/${id}/dismiss`,
    broadcast: '/notifications/broadcast',
  },

  // ---- payments ----
  // Paths mirror server payment.routes.js (mounted at `/api/payments`): the
  // payment list is `/payments/payments`, promos/refunds/subscriptions use the
  // plural server segments, and checkout/confirm take ids in the body or path
  // exactly as the routes declare them.
  payments: {
    webhook: '/payments/webhook',
    plans: '/payments/plans',
    checkoutExam: (examId) => `/payments/checkout/exam/${examId}`,
    checkoutCertification: (attemptId) => `/payments/checkout/certification/${attemptId}`,
    confirm: '/payments/confirm',
    promoValidate: '/payments/promo-codes/validate',
    promo: '/payments/promo-codes',
    promoById: (id) => `/payments/promo-codes/${id}`,
    refund: '/payments/refunds',
    list: '/payments/payments',
    revenue: '/payments/revenue',
    bulkRegistration: '/payments/bulk-registration',
    generateInvoice: (paymentId) => `/payments/invoices/${paymentId}/generate`,
    invoices: '/payments/invoices',
    invoice: (id) => `/payments/invoices/${id}`,
    subscription: (orgId) => `/payments/subscriptions/${orgId}`,
    upgrade: '/payments/subscriptions/upgrade',
    cancel: '/payments/subscriptions/cancel',
  },

  // ---- ai ----
  ai: {
    status: '/ai/status',
    usage: '/ai/usage',
    dailyUsage: '/ai/usage/daily',
    generateQuestions: '/ai/generate-questions',
    gradeEssay: '/ai/grade-essay',
    reviewCode: '/ai/review-code',
    cheatingRisk: '/ai/cheating-risk',
    calibrateDifficulty: '/ai/calibrate-difficulty',
    checkQuality: '/ai/check-quality',
    adaptiveSelect: '/ai/adaptive-select',
    personalizedFeedback: '/ai/personalized-feedback',
    retakeRecommendation: '/ai/retake-recommendation',
    blueprint: '/ai/blueprint',
    validateAnswerKey: '/ai/validate-answer-key',
    recommendQuestions: '/ai/recommend-questions',
    nlSearch: '/ai/nl-search',
    predictPassRate: '/ai/predict-pass-rate',
    summaryReport: '/ai/summary-report',
    proctorAssistant: '/ai/proctor-assistant',
    faceMatch: '/ai/face-match',
  },

  // ---- reports (PDF / CSV) ----
  reports: {
    certificatePdf: '/reports/certificate-pdf',
    invoicePdf: '/reports/invoice-pdf',
    resultPdf: '/reports/result-pdf',
    answerSheetPdf: '/reports/answer-sheet-pdf',
    analyticsPdf: '/reports/analytics-pdf',
    genericPdf: '/reports/generic-pdf',
    resultsCsv: '/reports/results-csv',
    analyticsCsv: '/reports/analytics-csv',
  },

  // ---- admin (platform) ----
  admin: {
    overview: '/admin/overview',
    health: '/admin/health',
    auditLogs: '/admin/audit-logs',
    organizations: '/admin/organizations',
    organization: (id) => `/admin/organizations/${id}`,
    approveOrganization: (id) => `/admin/organizations/${id}/approve`,
    suspendOrganization: (id) => `/admin/organizations/${id}/suspend`,
    reactivateOrganization: (id) => `/admin/organizations/${id}/reactivate`,
    deleteOrganization: (id) => `/admin/organizations/${id}`,
    users: '/admin/users',
    user: (userId) => `/admin/users/${userId}`,
    userRole: (userId) => `/admin/users/${userId}/role`,
    suspendUser: (userId) => `/admin/users/${userId}/suspend`,
    reactivateUser: (userId) => `/admin/users/${userId}/reactivate`,
    deleteUser: (userId) => `/admin/users/${userId}`,
    examCatalog: '/admin/exams/catalog',
    subscriptions: '/admin/subscriptions',
    plan: (planCode) => `/admin/plans/${planCode}`,
    revenue: '/admin/revenue',
    aiUsage: '/admin/ai-usage',
    proctoringIncidents: '/admin/proctoring-incidents',
    pendingCertificates: '/admin/certificates/pending',
    announcements: '/admin/announcements',
    announcement: (id) => `/admin/announcements/${id}`,
    settings: '/admin/settings',
    setting: (key) => `/admin/settings/${key}`,
    featureFlags: '/admin/feature-flags',
    featureFlag: (key) => `/admin/feature-flags/${key}`,
  },
};

export default endpoints;
